### ISSUE TITLE
svd2ada aborts with CONSTRAINT_ERROR for SVD\MK64F12.svd

### ISSUE THREAD

**Issue by jgrivera67** [AdaCore/svd2ada#22]
PS> .\svd2ada\svd2ada.exe -o SVD .\SVD\MK64F12.svd
**\* WARNING: ignoring device element vendorID
**\* WARNING: ignoring device element licenseText

raised CONSTRAINT_ERROR : bad input for 'Value: "2#1x#"
PS>

**Comment by lambourg** [comment]
That is the same issue as https://github.com/AdaCore/svd2ada/issues/2

You can fix it by replacing the "1x" value in the svd file by either 10 or 11.

**Comment by lambourg** [comment]
This should now be fixed also :)
