### ISSUE TITLE
Missing register in STM32F429x.svd

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/svd2ada#24]
While trying to prepare STM32F427x.svd for inclusion (an attempt I’ve now abandoned, since the 427 & 429 versions _should_ be almost identical, but aren’t, in important ways) I found the following minor difference between STM32F429x.svd and RM0090 (DocID018909 Rev 11):
- in I2C, the FLTR register with fields DNF, ANOFF is missing

Note, this was triggered by differences between the generated code for the two SVDs, _not_ by comparing the SVD to the RM.

**Comment by lambourg** [comment]
Hi Simon,

This is now fixed. Thanks for the notice !
I also found similar errors in the STM32F7x.svd file when trying out the STM32F7x9.svd file. Comparing the results of similar MCUs is interesting in this regard.
- Jerome
