### ISSUE TITLE
Error in generated code: component overlaps in record

### ISSUE THREAD

**Issue by euripedesrocha** [AdaCore/svd2ada#25]
I' trying to generate code for [atsamd4ls](ds.arm.com/media/resources/db/chip/atmel/atsam4ls2a/ATSAM4LS2A.svd). The code was generated with the svd file in the link using the following command without any issues:

svd2ada -p Interfaces.ATSAM4LS -o bsp

The build gives me the follwing problem:

i-atsam4ls-gpio.ads:2911:07: component "GPERS" overlaps "GPER" at line 2910

All fields in the record have the same problem. 

``` ada
   for GPIO_Peripheral use record
      GPER      at 0 range 0 .. 12287;
      GPERS     at 4 range 0 .. 12287;
      GPERC     at 8 range 0 .. 12287;
      GPERT     at 12 range 0 .. 12287;
...
  end record
```

I'm quite new to Ada, but it semms that the register is longer than it should be. I tried to change the sizes to 32 and it fixes the problem for a few lines:

``` ada
     GPER  at 0 range 0 .. 31
```

The error changes to a minimum size issue. I guess some registers are missing.

**Comment by euripedesrocha** [comment]
Working more on the issue, It seems to be the same case of Issue #5 .

**Comment by lambourg** [comment]
This indeed looks the same, and using the latest version of svd2ada, the generation is correct:

``` ada
   for GPIO_Peripheral use record
      GPER0      at 0 range 0 .. 31;
      GPERS0     at 4 range 0 .. 31;
      GPERC0     at 8 range 0 .. 31;
      GPERT0     at 12 range 0 .. 31;
...
      GPER1      at 512 range 0 .. 31;
```

Can you check that you're up-to-date?

**Comment by euripedesrocha** [comment]
You're correct. The most recent version doesn't have the issue. It was my fault. I forgot that I forked the repo, and this lead me to think that the code was up to date.
