### ISSUE TITLE
Base types not generated when using --base-types-package command line option

### ISSUE THREAD

**Issue by dgautherot** [AdaCore/svd2ada#37]
Hello,

When attempting to generate code using the STM32F7x.svd description with the following command line:
./svd2ada --output=STM32F7x-SVD --package=STM32F7x.SVD --base-types-package=STM32F7x --boolean --gen-uint-always CMSIS-SVD/ST/STM32F7x.svd

It appears that the base types (type UInt32, ...) are not generated at all, even in STM32F7x.SVD package (in which i find the base addresses) or in STM32F7x (which does not exist).

Am i doing something wrong with the command line parameters or is this really an issue ?

In the meantime, I will check in the source code if I see where this issue is coming from.

Thanks.

Denis.

**Comment by lambourg** [comment]
Hello Denis,

The --base-types-package tells svd2ada that the base types are located in an external package (in this case STM32F7x), so it should reference them there instead of generating them.

Removing this switch should solve your issue.
