### ISSUE TITLE
STM32F446 svd file fail

### ISSUE THREAD

**Issue by mterron** [AdaCore/svd2ada#38]
When trying to process the svd for the STM32F446 I get this output:
```
$ svd2ada -o STM32F446 STM32F446x.svd
Creating Dir /tmp/keil/CMSIS/SVD/STM32F446x
Generate DCMI
Generate FSMC
Generate DBG
Generate DMA
Generate RCC
Generate GPIO
Generate SYSCFG
Generate SPI
Generate SDIO
Generate ADC
Generate USART
Generate DAC
Generate I2C
Generate IWDG
Generate WWDG
Generate RTC
Generate TIM
Generate CRC
Generate USB_OTG_FS
Generate CAN
Generate NVIC
Generate FLASH
Generate EXTI
Generate USB_OTG_HS
Generate SAI
Generate PWR

raised CONSTRAINT_ERROR : bad input for 'Value: ""
```

Error is not very helpful. Would it be correct to assume that it's something on the PWR peripheral?

**Comment by lambourg** [comment]
I just pushed a fix. This was an improper copy/paste in field names comparison. I also fix another error that would have led in this case into confusing code being generated for PWR.CSR.EWUP2 and EWUP registers.
