### ISSUE TITLE
README.md: add the parameters used in Ada_Drivers_Library

### ISSUE THREAD

**Issue by AlexusEl** [AdaCore/svd2ada#55]
Hi,
To make easy adding new svd chips, can you please specify the parameters (--boolean, --no-uint-subtypes,...) that you use by default in the reposit Ada_Drivers_Library to generate the Ada's SVD.
Thank you for your support,
Regards,
Badr

**Comment by Fabien-Chouteau** [comment]
Hi @HackInvent,

Thanks for the feedback, I think it would make more sense to document in Ada_Drivers_Library how we use svd2ada.

The SVD generated sources of Ada_Drivers_Library all come from this makefile: https://github.com/AdaCore/Ada_Drivers_Library/blob/master/arch/svd.mk

This is the kind of info we have document in a porting guide.
