### ISSUE TITLE
Generated filenames in Interfaces hierarchy

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/svd2ada#6]
If I use `-p Interfaces`, all the files are generated at the top level (`i-flash.ads`, for example).

If I use `-p Interfaces.STM32F429x`, the files are generated as `i-stm32f429x-flash.ads`, which the compiler doesn’t like; it would prefer `i-stmfla.ads`, and generates a warning, which I’m pretty sure isn’t allowed with `-gnatg`.

One workround would be to generate `interfaces-stm32f429x-flash.ads` and then use gnatkr and a shell script ..

**Comment by lambourg** [comment]
Hello Simon,

The generation of the Interfaces.\* hierarchy is not yet ready for prime time use. It requires the next-generation gnat compilation toolchain (e.g. GNAT GPL 2016) to support the un-krunching of part of the runtime. Moreover, it really is dedicated to very low-level runtime support for booting a board (low-level in the sense that the runtime is not elaborated yet when such package is used), and only that. It is expected for the drivers layer to generate their own binding hierarchy.

As a workaround, you can still rename the files, potentially with the help of gnatchop. This however will certainly involve name clashes (such as Interfaces.STM32.DMA2D and Interfaces.STM32.DMA being both krunched as i-stmdma.ads).

As a result, I don't intend to fix anything there... So I'm closing this issue.

Best regards,
- Jerome
