### ISSUE TITLE
Why bit field value name casing is modified ?

### ISSUE THREAD

**Issue by NicoPy** [AdaCore/svd2ada#65]
Here is an example of the description of a bit field generated by svd2ada :

```ada
   --  VREF Clock Gate Control
   type SCGC40_VREF_Field is
     (--  Clock disabled
      Clockdisabled,
      --  Clock enabled
      Clockenabled)
     with Size => 1;
   for SCGC40_VREF_Field use
     (Clockdisabled => 0,
      Clockenabled => 1);
```
`Clockdisabled` and `Clockenabled` are defined respectively as `ClockDisabled` and `ClockEnabled` in the svd file.
Why is the casing modified ? 
This makes field names hard to read. Especially long ones.
Try to read this one Flashisdisabledduringwaitmode or this one K4xfamilyork2xfamilywithtamper ;)

**Comment by Fabien-Chouteau** [comment]
Hello @NicoPy,

> Why is the casing modified ?

`svd2ada` generates code that follow the GNAT coding style so the identifiers use combination of snake and camel case: `Like_This`

> This makes field names hard to read. Especially long ones.
> Try to read this one Flashisdisabledduringwaitmode or this one K4xfamilyork2xfamilywithtamper ;)

We could either convert everything to snake camel case by inserting underscores before capital letters: `Clock_Enabled`

Or have the option to keep casing: `ClockEnable`

CC @pat-rogers @lambourg

**Comment by NicoPy** [comment]
Why not add an option to select which style to use during conversion ?

**Comment by Fabien-Chouteau** [comment]
Yes that is a possibility.

**Comment by pat-rogers** [comment]
>     This makes field names hard to read. Especially long ones.
>     Try to read this one Flashisdisabledduringwaitmode or this one
>     K4xfamilyork2xfamilywithtamper ;)
> 
> We could either convert everything to snake camel case by inserting 
> underscores before capital letters: |Clock_Enabled|

Although that is the most readable, IMO, does it not open the 
possibility of introducing homonyms?  Or can we know that both styles 
are never used together in the same input file? In this case perhaps 
not, although I have seen it done in user-written code.

> Or have the option to keep casing: |ClockEnable|

That seems like the right default to me, under the circumstances. Not 
that I find that style very readable either.

**Comment by Matthias-R** [comment]
> That seems like the right default to me, under the circumstances. 

Definitely yes. The reference when working with a microcontroller is the datasheet and/or the programming manual - and the naming in the .svd file is [should be] identical to the manual.
It would be a nightmare when the .ads file was different - you have to guess where underscores have been inserted.
I don't really like CamelCase either, but in my opinion it is more readable than everythinginlowercase.

**Comment by pat-rogers** [comment]
On 11-May-20 12:58 PM, Matthias Richter wrote:
>     That seems like the right default to me, under the circumstances.
> 
> Definitely yes. The reference when working with a microcontroller is the 
> datasheet and/or the programming manual - and the naming in the .svd 
> file is [should be] identical to the manual.
> It would be a nightmare when the .ads file was different - you have to 
> guess where underscores have been inserted.

Agreed.

> I don't really like CamelCase either, but in my opinion it is more 
> readable than everythinginlowercase.

My favorite is spaceperson, which could be either space_person or 
space_per_son. :-)

**Comment by NicoPy** [comment]
So, what's the final decision ?

**Comment by pat-rogers** [comment]
On 24-May-20 8:09 AM, Nicolas Pinault wrote:
> So, what's the final decision ?

We'll make it retain the casing encountered in the SVD input.

**Comment by NicoPy** [comment]
Ok. Great.
Thanks for your support.

**Comment by pat-rogers** [comment]
Our pleasure.

**Comment by pat-rogers** [comment]
The letter casing for enumerals is now retained unchanged from the SVD input file.

**Comment by pat-rogers** [comment]
On 28-May-20 11:23 AM, Nicolas Pinault wrote:
> Ok. Great.
> Thanks for your support.

You're very welcome.

Note that the change has been applied to enumeration type values, 
specifically.  I didn't see any other occurrences but may have missed 
one. Let me know if you see any others.

**Comment by NicoPy** [comment]
I have not noticed any other occurrence till now. I'll let you know if I find one.
Thanks again.
