### ISSUE TITLE
Style error on field

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/svd2ada#7]
If a field has no description, e.g.

```
        <field>
          <name>TSTP</name>
          <bitOffset>23</bitOffset>
          <bitWidth>1</bitWidth>
          <access>read-only</access>
        </field>
```

then the generated code has a comment with a trailing space, which gives a style error with -gnatpg.

```
476.       --  Read-only. 
                         |
     >>> (style) trailing spaces not permitted

477.       TSTP          : SR_TSTP_Field;
```

**Comment by lambourg** [comment]
Hi Simon,

Thank you very much for your sanity checks! Very much appreciated :) This issue should now be fixed. Can you check?

Best regards,
Jerome

**Comment by simonjwright** [comment]
Jerome,

Thanks for quick fix! Minor problem (which results in CE!), see patch attached.

[strip_string.diff.txt](https://github.com/AdaCore/svd2ada/files/170646/strip_string.diff.txt)

**Comment by simonjwright** [comment]
Now fixed, thanks.

**Comment by lambourg** [comment]
You're welcome!
