### ISSUE TITLE
Comment fields should come after the generated code and not before

### ISSUE THREAD

**Issue by kevlar700** [AdaCore/svd2ada#89]
If you look at the following files in an IDE and especially line 741 of the first link (stm32-device.adb).
         `RCC_Periph.APB2RSTR.SDMMC1RST := True;`

"https://github.com/AdaCore/Ada_Drivers_Library/blob/master/arch/ARM/STM32/devices/stm32f7x9/stm32-device.adb"
"https://github.com/AdaCore/Ada_Drivers_Library/blob/master/arch/ARM/STM32/svd/stm32f7x9/stm32_svd-rcc.ads"

And hover/highlight over e.g. `SDMMC1RST` in an IDE then you will see the wrong comment (SPI 1 reset) instead of "SDMMC2 reset".

Generally not much of an issue but it could be confusing when the names are less obvious.

**Comment by kevlar700** [comment]
Record comments are probably best left where they are as they do not seem to be interpreted by IDEs? I'm not sure about other types but this commit solves most if not all of the practical issue for me by changing just the comment location of record fields. Variant record comments stay in the same place above. They should also move below but I haven't found where they are generated, yet.

https://github.com/kevlar700/svd2ada/commit/255c5786ec34cbd21a202852138ce1a28573f312

**Comment by kevlar700** [comment]
Found the discriminated variant record fix. Light testing has been done also.
https://github.com/kevlar700/svd2ada/commit/e29ffb4d8f7b99efea2209d422c7e519080a1065

**Comment by pat-rogers** [comment]
Really I think this will be tricky because it is up to the IDE to decide 
which line(s) to display. IIRC, the choice has changed over time.

I wonder if there is an IDE option to control it.

**Comment by kevlar700** [comment]
Interesting. I shall look out for IDE options but I believe that was my first port of call. I suppose the other option is a runtime flag. These patches make the record comments correct for me on GNAT Studio and VsCode and so may be helpful to others, atleast.

**Comment by pat-rogers** [comment]
On 17-Mar-22 10:29 AM, Kevin Chadwick wrote:
> Interesting. I shall look out for IDE options but I believe that was my 
> first port of call. I suppose the other option is a runtime flag. These 
> patches make the record comments correct for me on GNAT Studio and 
> VsCode and so may be helpful to others, atleast.

I'll check with the IDE team to see what they recommend.

**Comment by kevlar700** [comment]
I have the same issue with enumerated values now which I did not know svd2ada supported until recently. ST have started putting much longer descriptions in their SVD files, which is nice too.
I guess any kind of consensus or IDE option was not forthcoming? I believe most languages put comments above, or to the right and Gnat Studio supports Ada, C and now Rust. I would be happy if everything followed that style?

https://doc.rust-lang.org/book/ch03-04-comments.html.

Perhaps this is a language server issue.

**Comment by kevlar700** [comment]
The leading setting may well be the answer. It is easy to apply to vscode but I am having difficulty with Gnat Studio.

https://github.com/AdaCore/ada_language_server/blob/master/doc/settings.md#documentationstyle

**Comment by kevlar700** [comment]
This seems to be working now in the latest Gnat Studio CR 25.0w (20240506) simply by setting the check box for leading documentation in preferences => Documentation and restarting Gnat Studio or the language server. I assume that I tried restarting Gnat Studio before after setting it but in any case I am quite happy with using this as my default now. I shall close this issue but feel free to re-open it if you still think there is an issue to deal with in terms of svd2adas default.
