### ISSUE TITLE
No script or documentation for integrating it into the Ada toolchain

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/svd2ada#90]
It would be nice if the build scripts collected the build artifacts into a single application folder containing all the necessary dependencies which can be installed as part of the build chain. Currently, you have to either run it from the project folder, or painstakingly determine the dependent files for installation into the toolchain path.

**Comment by Fabien-Chouteau** [comment]
Which build artifacts are you referring to?

**Comment by Joebeazelman** [comment]
By build artifact, I mean files required for running it that will be deployed on the system, or the equivalent of "make install." After downloading the repository and building it, there's no instruction or scripts for deploying it into the system. I presume just copying the svd2ada executable to my local bin isn't enough. It probably needs additional directories and files. Ideally, I wish I could install it using ALR, but I couldn't find it as a package.

**Comment by Fabien-Chouteau** [comment]
Hello @Joebeazelman 

svd2ada is not available in Alire!
