### ISSUE TITLE
What's the purpose of the --package switch?

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/svd2ada#93]
What's the purpose of the **--package** switch? I haven't been able to locate any documentation on it.  Is it for specifying a top-level package name along with common infrastructure for a set of generated devices under the same device family or series? Also, what's the difference between a runtime package and a standard package?  

```
Define_Switch
        (Cmd_Line_Cfg,
         Output      => Root_Pkg_Name'Access,
         Switch      => "-p=",
         Long_Switch => "--package=",
         Help        => "the root package name for the generated spec hierarchy",
         Argument    => "Pkg_Name");
```

```
if Root_Pkg_Name.all /= "" then
         Set_Root_Package (Root_Pkg_Name.all);

         --  If Pkg is a runtime package, force the generation of Interrupts.Names
         --  and IRQ trap vector.
         if SVD2Ada_Utils.In_Runtime then
            Gen_IRQ_Support := True;
         end if;
 end if;
```

**Comment by Fabien-Chouteau** [comment]
Hello @Joebeazelman 

This is the name of the root package for the packages that will be generated:
```
$ svd2ada --package nRF51_SVD [...]
Generating package nRF51_SVD
Generating package nRF51_SVD.POWER
Generating package nRF51_SVD.CLOCK
[...]
$ svd2ada --package nRF51_SOMETHING_ELSE [...]
Generating package nRF51_SOMETHING_ELSE
Generating package nRF51_SOMETHING_ELSE.POWER
Generating package nRF51_SOMETHING_ELSE.CLOCK
[...]
```

There's a special handling when the root package is under `System.` because that's part of the run-time and the output is different. You should not need to use that.
